baseURL: "https://hadjshell.github.io/"
title: Hadjshell
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Hadjshell Blog Site
  description: "Hadjshell Blog Site"
  keywords: [Blog, Hadjshell, PaperMod]
  author: Hadjshell
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "Jan 2 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Hadjshell"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # # home-info mode
  # homeInfoParams:
  #   Title: "Hi there welcome to Hadjshell's field\U0001F44B"
  #   Content: Mind and hand 知行合一

  # socialIcons:
  #   - name: linkedin
  #     url: "https://www.linkedin.com/in/jiayuan-zhang-00390a201/"
  #   - name: github
  #     url: "https://github.com/hadjShell"
  #   - name: instagram
  #     url: "https://www.instagram.com/hadjshell/"

  profileMode:
    enabled: true
    title: "Welcome to Hadjshell's field\U0001F44B" # optional default will be site title
    imageUrl: "https://hadjshell.github.io/logo.JPG" # optional
    imageTitle: "Hadjshell's Logo" # optional
    imageWidth: 150 # custom size
    imageHeight: 150 # custom size

  socialIcons: # optional
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/jiayuan-zhang-00390a201/"
    - name: "Github"
      url: "https://github.com/hadjShell"
    - name: "email"
      url: "mailto:contact@davidzhang0880@gmail.com"
    - name: "instagram"
      url: "https://www.instagram.com/hadjshell/"
    - name: "rss"
      url: "https://hadjshell.github.io/index.xml"
    - name: "buymeacoffee"
      url: "https://buymeacoffee.com/davidzhang0"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

menu:
  main:
    - identifier: Home
      name: Home
      url: /
      weight: 10
    - identifier: Archives
      name: Archives
      url: /archives/
      weight: 20
    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 30
    - identifier: About Me
      name: About Me
      url: /about/
      weight: 40

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
